### ISSUE TITLE
Feature request : look up the Salesforce Metadata Coverage Report

### ISSUE THREAD

**Issue by RupertBarrow** [Oblongmana/vscode-salesforce-doc-lookup#13]
A dream I have would be to be able to look up the Metadata Coverage Report directly from VS Code, with autocomplete, etc.
If not, please add opening the Metadata Coverage Report from VS Code : 
https://developer.salesforce.com/docs/metadata-coverage/

**Comment by Oblongmana** [comment]
Hi again @RupertBarrow !

Hooking into autocomplete is a little beyond the scope of this extension, at least for now, but I should be able to integrate the metadata coverage report as a new doc type

It's quite different to the format of the Atlas and Aura app based doc types the extension already supports, but the good news is there's a JSON table of contents we can hit that I believe contains all the info needed to support both approaches to searching and accessing doc that the extension uses:
- linking out to specific metadata types in browser (e.g. linking to Quick action: https://developer.salesforce.com/docs/metadata-coverage/55/QuickAction/), and 
- building a facsimile of that Metadata Type's information (from all tabs) on the fly in a VSCode WebView if you have the `vscode-salesforce-doc-lookup.EXPERIMENTAL.useWebview` setting enabled

[I've sketched out notes and an approach here](https://github.com/Oblongmana/vscode-salesforce-doc-lookup/blob/feature/restructure-2022-07/notes/metadata_coverage_notes.md), and am hoping to get that [restructure branch](https://github.com/Oblongmana/vscode-salesforce-doc-lookup/tree/feature/restructure-2022-07) wrapped up in the next couple of weeks - with a few new features, allowing lang and release version overrides per doc type, adding some additional doc types. 

Will tag you once it's shipped! 🚢

Edit: unfortunately discovered while you can link direct to a pop-up for a Metadata Type (e.g. https://developer.salesforce.com/docs/metadata-coverage/55/QuickAction/), the js app's in-page routing discards further info when accessing the page cold, so you can't e.g. link directly to the Scratch Def tab (e.g. https://developer.salesforce.com/docs/metadata-coverage/55/QuickAction/scratch-def/group). Have updated above comments and the discover/impl notes in the repo, there's still a sensible approach for this one 👍

**Comment by Oblongmana** [comment]
I've made a full working version of this without discovering any further insurmountable hurdles, so expecting to ship this in the next release 🚢 

Feature set/screenshots:

- Search granularity level: Whole report or individual metadata type ![image](https://user-images.githubusercontent.com/1976919/179323301-663215c6-3ec4-451a-83d5-0bb8bfdd1672.png)
- Link out to live webpage if setting `"vscode-salesforce-doc-lookup.EXPERIMENTAL.useWebview": false`
- VSCode WebView reconstruction of the page if setting `"vscode-salesforce-doc-lookup.EXPERIMENTAL.useWebview": true`, including ability to copy scratch org json examples. Of course, has some adaptations to make this work in the VSCode WebView, and is a relatively speedy implementation, rather than a full fledged SPA!
![image](https://user-images.githubusercontent.com/1976919/179323471-8343ccb8-e9a3-4de8-8678-72b5018629c3.png)
- WebView page also works for single items, not just the full report 
![image](https://user-images.githubusercontent.com/1976919/179326922-65264b7a-4341-4b53-8971-14e297c5aeea.png)
- Per-workspace-settings (or global if you want) version code override: ![image](https://user-images.githubusercontent.com/1976919/179323254-39e4638b-4f08-4f2c-8acf-96bdd2e9dc35.png)

**Comment by Oblongmana** [comment]
@RupertBarrow The extension update (2.0.0) is now live, so closing this as complete, with the above included. If you hit any issues or anything, please do let me know! 🙏
